//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:08:59 PM CET 
//


package rs.ac.uns.ftn.jaxb.example3;

import java.util.Date;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import rs.ac.uns.ftn.jaxb.util.MyDatatypeConverter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (MyDatatypeConverter.parseDate(value));
    }

    public String marshal(Date value) {
        return (MyDatatypeConverter.printDate(value));
    }

}
